// <auto-generated />
using System;
using FCSTApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FCSTApplication.Migrations
{
    [DbContext(typeof(FCSTApplicationContext))]
    partial class FCSTApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FCSTApplication.Models.CoalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BohaiInventory")
                        .HasColumnType("int");

                    b.Property<int?>("CoalPrice_5000")
                        .HasColumnType("int");

                    b.Property<int?>("CoalPrice_5500")
                        .HasColumnType("int");

                    b.Property<int?>("CoalPrice_5800")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliveryFee")
                        .HasColumnType("int");

                    b.Property<int?>("NewcPrice")
                        .HasColumnType("int");

                    b.Property<int?>("PortChinInventory")
                        .HasColumnType("int");

                    b.Property<int?>("SpotPrice_5500")
                        .HasColumnType("int");

                    b.Property<string>("Week")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoalData");
                });

            modelBuilder.Entity("FCSTApplication.Models.StarchData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChinaShandongPrice")
                        .HasColumnType("int");

                    b.Property<int?>("CornPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThaiPrice")
                        .HasColumnType("int");

                    b.Property<string>("Week")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WheatPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StarchData");
                });
#pragma warning restore 612, 618
        }
    }
}
